from channels.generic.websocket import WebsocketConsumer, AsyncWebsocketConsumer
import json
from urllib.parse import parse_qs
from channels.db import database_sync_to_async
from .models import *
from .services.vote_store import VoteStorageService

vote_storage = VoteStorageService()

class SessionConsumer(AsyncWebsocketConsumer):

    async def connect(self):
        self.session_id = self.scope["url_route"]["kwargs"]["session_id"]

        self.room_group_name = f"session_{self.session_id}"
        print("="*50)
        headers = dict(self.scope.get("headers", []))
        print("WEBSOCKET HEADERS:", headers)

        user_id = headers.get(b"x-user-id")

        print("USER ID FROM HEADER:", user_id)

        if not user_id:
            await self.close(code=4001)
            return

        self.user_id = int(user_id.decode())

        session = await database_sync_to_async(
            Session.objects.filter(id=self.session_id).first
        )()

        await self.accept()

        if not session:
            await self.send(
                text_data=json.dumps({
                    "type": "error",
                    "message": "Session not found."
                })
            )

            await self.close(code=4004)
            return
        
        if session.status != Session.Status.ACTIVE:
            await self.send(
                text_data=json.dumps({
                    "type": "error",
                    "message": "Session is not active."
                })
            )
            await self.close(code=4003)
            return

        participant = await database_sync_to_async(
            SessionParticipant.objects.filter(
                session=session,
                user_id=self.user_id
            ).exists
        )()

        if not participant:
            await self.send(
                text_data=json.dumps({
                    "type": "error",
                    "message": "You are not a participant in this session."
                })
            )
            await self.close(code=4001)
            return

        await self.channel_layer.group_add(
            self.room_group_name,
            self.channel_name, # automaticlly generated by the server 
        )

        

    async def disconnect(self, close_code):
        await self.channel_layer.group_discard(
            self.room_group_name,
            self.channel_name,
        )

    # async def chat_message(self, event):
    #     await self.send(
    #         text_data=json.dumps({
    #             "message": event["message"]
    #         })
    #     )

    async def check_session_finished(self):
        participants = await database_sync_to_async(
            lambda: list(
                SessionParticipant.objects.filter(
                    session_id=self.session_id
                ).values_list(
                    "user_id",
                    flat=True,
                )
            )
        )()

        all_finished = await vote_storage.all_users_finished(
            self.session_id,
            participants,
        )

        if not all_finished:
            return

        winner = await vote_storage.get_winner(
            self.session_id,
        )

        session = await database_sync_to_async(
            Session.objects.get
        )(id=self.session_id)

        if winner:
            await database_sync_to_async(session.end)(winner)

            await self.channel_layer.group_send(
                self.room_group_name,
                {
                    "type": "movie_selected",
                    "movie_id": winner,
                }
            )

        else:
            await database_sync_to_async(session.end)(None)

            await self.channel_layer.group_send(
                self.room_group_name,
                {
                    "type": "no_winner",
                }
            )

        await vote_storage.clear_session(
            self.session_id,
            participants,
        )

    async def get_participant_ids(self):
        return await database_sync_to_async(
            lambda: list(
                SessionParticipant.objects.filter(
                    session_id=self.session_id
                ).values_list("user_id", flat=True)
            )
        )()


    async def handle_like(self):
        session = await database_sync_to_async(
            Session.objects.filter(id=self.session_id).first
        )()

        if not session or session.status != Session.Status.ACTIVE:
            return

        current_movie = await vote_storage.get_current_movie(
            self.session_id,
            self.user_id,
        )

        if current_movie is None:
            return

        likes = await vote_storage.like_movie(
            self.session_id,
            current_movie,
        )

        participant_count = await database_sync_to_async(
            lambda: SessionParticipant.objects.filter(
                session_id=self.session_id
            ).count()
        )()

        participant_ids = await database_sync_to_async(
                lambda: list(
                    SessionParticipant.objects.filter(
                        session_id=self.session_id
                    ).values_list(
                        "user_id",
                        flat=True
                    )
                )
            )()

        if likes == participant_count:

            movie = await vote_storage.get_movie_details(
                self.session_id,
                current_movie
            )

            await database_sync_to_async(session.end)(current_movie)

            await self.channel_layer.group_send(
                self.room_group_name,
                {
                    "type": "movie_selected",
                    "movie": movie,
                }
            )

            await vote_storage.clear_session(
                self.session_id,
                participant_ids,
            )

            return

        await vote_storage.increment_index(
            self.session_id,
            self.user_id,
        )

        next_movie = await vote_storage.get_current_movie(
            self.session_id,
            self.user_id,
        )

        await self.send(
            text_data=json.dumps({
                "type": "next_movie",
                "movie_id": next_movie,
            })
        )

        await self.channel_layer.group_send(
            self.room_group_name,
            {
                "type": "movie_liked",
                "movie_id": current_movie,
                "likes": likes,
            }
        )

        finished = await vote_storage.is_user_finished(
            self.session_id,
            self.user_id,
        )

        if finished:
            await self.check_session_finished()

    async def handle_dislike(self):
        session = await database_sync_to_async(
            Session.objects.filter(id=self.session_id).first
        )()

        if not session or session.status != Session.Status.ACTIVE:
            return

        current_movie = await vote_storage.get_current_movie(
            self.session_id,
            self.user_id,
        )

        if current_movie is None:
            return

        await vote_storage.increment_index(
            self.session_id,
            self.user_id,
        )

        next_movie = await vote_storage.get_current_movie(
            self.session_id,
            self.user_id,
        )

        await self.send(
            text_data=json.dumps({
                "type": "next_movie",
                "movie_id": next_movie,
            })
        )

        finished = await vote_storage.is_user_finished(
            self.session_id,
            self.user_id,
        )

        if finished:
            await self.check_session_finished()

    async def receive(self, text_data):
        data = json.loads(text_data)

        message_type = data.get("type")

        if message_type == "like":
            await self.handle_like()

        elif message_type == "dislike":
            await self.handle_dislike()

        else:
            await self.send(
                text_data=json.dumps({
                    "type": "error",
                    "message": "Invalid message type."
                })
            )

        # print(f"Received: {text_data} in {self.room_group_name}")
        # await self.send(text_data=text_data)
        # await self.channel_layer.group_send(
        #     self.room_group_name,
        #     {
        #         "type": "chat_message",
        #         "message": text_data,
        #     }
        # )

    async def movie_liked(self, event):
        await self.send(
            text_data=json.dumps({
                "type": "movie_liked",
                "movie_id": event["movie_id"],
                "likes": event["likes"],
            })
        )
    
    async def movie_selected(self, event):

        await self.send(
            text_data=json.dumps({
                "type": "movie_selected",
                "movie": event["movie"],
            })
        )

        await self.close()

    async def no_winner(self, event):
        await self.send(
            text_data=json.dumps({
                "type": "no_winner",
            })
        )
        await self.close()

    async def member_joined(self, event):
        await self.send(
            text_data=json.dumps({
                "type": "member_joined",
                "user_id": event["user_id"],
            })
        )
    
    async def session_started(self, event):
        await self.send(
            text_data=json.dumps({
                "type": "session_started",
                "session_id": event["session_id"],
            })
        )
    
    async def session_ended(self, event):
        await self.send(
            text_data=json.dumps({
                "type": "session_ended",
                "movie_tmdb_id": event["movie_tmdb_id"],
            })
        )